presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-cross
    run_if_changed: '^((build\/|hack\/lib\/).*)|(.*Makefile.*)$'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/bootstrap:v20200430-be2a8a9
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - --scenario=execute
        - --
        - --env=KUBE_RELEASE_RUN_TESTS=n
        - make
        - release
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7
            memory: "41Gi"
    annotations:
      testgrid-create-test-group: 'true'

periodics:
- interval: 1h
  name: ci-kubernetes-build
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bootstrap:v20200430-be2a8a9
      args:
      - --repo=k8s.io/kubernetes
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=180
      - --scenario=kubernetes_build
      - --
      - --allow-dup
      - --extra-publish-file=latest-cross,k8s-master
      - --registry=gcr.io/kubernetes-ci-images
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 4
          memory: "8Gi"
  rerun_auth_config:
    github_team_ids:
      - 2241179 # release-managers
  annotations:
    fork-per-release: "true"
    fork-per-release-replacements: "latest-cross -> latest-{{.Version}}-cross, k8s-master -> k8s-beta"
    testgrid-dashboards: sig-release-master-blocking
    testgrid-tab-name: build-master
    testgrid-alert-email: release-managers@kubernetes.io, kubernetes-release-team@googlegroups.com

- interval: 5m
  name: ci-kubernetes-build-fast
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bootstrap:v20200430-be2a8a9
      args:
      - --repo=k8s.io/kubernetes
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=30
      - --scenario=kubernetes_build
      - --
      - --allow-dup
      - --fast
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 4
          memory: "8Gi"
  rerun_auth_config:
    github_team_ids:
      - 2241179 # release-managers
  annotations:
    testgrid-dashboards: sig-release-master-blocking, google-unit
    testgrid-tab-name: build-master-fast
    testgrid-alert-email: kubernetes-release-team@googlegroups.com
    description: 'Ends up running: make quick-release'

- interval: 4h
  name: ci-release-build-packages-debs
  decorate: true
  spec:
    containers:
    - image: gcr.io/k8s-staging-releng/kubepkg:latest
      imagePullPolicy: Always
      command:
      - ./kubepkg
      args:
      - debs
      resources:
        requests:
          cpu: 4
          memory: "8Gi"
  rerun_auth_config:
    github_team_ids:
      - 2241179 # release-managers
  annotations:
    testgrid-alert-email: release-managers@kubernetes.io
    testgrid-dashboards: sig-release-releng-informing
    testgrid-tab-name: build-packages-debs

- interval: 4h
  name: ci-release-build-packages-rpms
  decorate: true
  spec:
    containers:
    - image: gcr.io/k8s-staging-releng/kubepkg-rpm:latest
      imagePullPolicy: Always
      command:
      - ./kubepkg
      args:
      - rpms
      resources:
        requests:
          cpu: 4
          memory: "8Gi"
  rerun_auth_config:
    github_team_ids:
      - 2241179 # release-managers
  annotations:
    testgrid-alert-email: release-managers@kubernetes.io
    testgrid-dashboards: sig-release-releng-informing
    testgrid-tab-name: build-packages-rpms
