periodics:
# Runs e2e on the cluster built with latest released kops and latest released k/k
- interval: 1h
  labels:
    preset-k8s-ssh: "true"
  name: e2e-kops-gce-stable
  decorate: true
  decoration_config:
    timeout: 140m
  spec:
    serviceAccountName: k8s-kops-test
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-gce-stable.k8s.local
      - --deployment=kops
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/latest.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/latest
      - --ginkgo-parallel
      - --kops-args=--gce-service-account=pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --kops-zones=us-central1-c
      - --provider=gce
      - --timeout=140m
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Firewall|Dashboard|Services.*functioning.*NodePort
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-kops-gce, kops-gce
    testgrid-tab-name: kops-gce-stable

# Runs e2e on the cluster built with latest released kops and k/k master branch
- interval: 1h
  labels:
    preset-k8s-ssh: "true"
  name: e2e-kops-gce-latest
  decorate: true
  decoration_config:
    timeout: 140m
  spec:
    serviceAccountName: k8s-kops-test
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-gce-latest.k8s.local
      - --deployment=kops
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release-dev/ci/k8s-master.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=ci/k8s-master
      - --ginkgo-parallel
      # Temporarily use default service account: https://github.com/kubernetes/test-infra/issues/17558
      #- --kops-args=--gce-service-account=pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --kops-zones=us-central1-c
      - --provider=gce
      - --timeout=140m
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Firewall|Dashboard|Services.*functioning.*NodePort
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-kops-gce, kops-gce
    testgrid-tab-name: kops-gce-latest

# Runs e2e on cluster built with kops master branch and latest released k/k
- interval: 1h
  labels:
    preset-k8s-ssh: "true"
  name: e2e-kops-canary-gce-stable
  decorate: true
  decoration_config:
    timeout: 140m
  spec:
    serviceAccountName: k8s-kops-test
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-canary-gce-stable.k8s.local
      - --deployment=kops
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/latest.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/latest
      - --ginkgo-parallel
      - --kops-args=--gce-service-account=pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
      - --kops-build
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-zones=us-central1-c
      - --provider=gce
      - --timeout=140m
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Firewall|Dashboard|Services.*functioning.*NodePort
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-kops-gce, kops-gce
    testgrid-tab-name: kops-canary-gce-stable

# - interval: 30m
#   name: e2e-kops-gce-ha
#   labels:
#     preset-service-account: "true"
#     preset-k8s-ssh: "true"
#   decorate: true
#   decoration_config:
#     timeout: 140m
#   spec:
#     containers:
#     - command:
#       - runner.sh
#       - /workspace/scenarios/kubernetes_e2e.py
#       args:
#       - --cluster=e2e-kops-gce-ha.k8s.local
#       - --deployment=kops
#       - --extract=ci/latest
#       - --ginkgo-parallel=30
#       - --kops-args=--master-count=3
#       - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
#       - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-gce-green.txt
#       - --kops-zones=us-central1-c
#       - --provider=gce
#       - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
#       - --timeout=120m
#       image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
#   annotations:
#     testgrid-dashboards: sig-cluster-lifecycle-kops, google-kops-gce, kops-gce
#     testgrid-tab-name: kops-gce-ha
