periodics:

# Verify the latest-ci-updown-green version of kops, against most of the e2e tests
# Publishes gs://kops-ci/bin/latest-ci-green.txt
- interval: 1h
  name: e2e-kops-aws-k8s-latest
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
    preset-e2e-platform-aws: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-latest.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release-dev/ci/k8s-master.txt
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=ci/k8s-master
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-publish=gs://kops-ci/bin/latest-ci-green.txt
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-latest

- interval: 2h
  name: e2e-kops-aws-k8s-1-18
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-18.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-1.18

- interval: 2h
  name: e2e-kops-aws-k8s-1-17
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-17.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.17.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.17
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-1.17

- interval: 2h
  name: e2e-kops-aws-k8s-1-16
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-16.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.16.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.16
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.16
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-1.16

- interval: 8h
  name: e2e-kops-aws-k8s-1-15
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-15.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.15.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.15
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200623-2424179-1.15
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-1.15

- interval: 8h
  name: e2e-kops-aws-k8s-1-14
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-14.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.14.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.14
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.14
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-1.14

- interval: 8h
  name: e2e-kops-aws-k8s-1-13
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-13.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.13.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.13
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource|SchedulerPredicates|Lease
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.13
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-1.13

- interval: 8h
  name: e2e-kops-aws-k8s-1-12
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-12.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.12.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.12
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource|SchedulerPredicates|Lease|hostAliases|NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.12
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-1.12

- interval: 8h
  name: e2e-kops-aws-k8s-1-11
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-11.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.11.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.11
      - --ginkgo-parallel
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource|SchedulerPredicates|Lease|hostAliases|NodePort
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-1.11
      imagePullPolicy: Always
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-tab-name: kops-aws-k8s-1.11
