presubmits:
  kubernetes/kops:
  - name: pull-kops-bazel-build
    always_run: true
    skip_report: false
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "bazel-build"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: bazel-build
  - name: pull-kops-bazel-test
    always_run: true
    skip_report: false
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "bazel-test"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: bazel-test
  - name: pull-kops-e2e-kubernetes-aws
    branches:
    - master
    always_run: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-e2e-platform-aws: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
        imagePullPolicy: Always
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --check-leaked-resources=false
        - --cluster=
        - --kops-ssh-user=ubuntu
        - --env=KUBE_SSH_USER=ubuntu
        - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/latest-1.19.txt
        - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
        - --env=KOPS_RUN_TOO_NEW_VERSION=1
        - --extract=release/latest-1.19
        - --ginkgo-parallel
        - --kops-build
        - --kops-priority-path=/home/prow/go/src/k8s.io/kops/kubernetes/platforms/linux/amd64
        - --provider=aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
        - --timeout=55m
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: e2e
  - name: pull-kops-e2e-kubernetes-aws-1-16
    branches:
    - release-1.16
    always_run: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-e2e-platform-aws: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
        imagePullPolicy: Always
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --check-leaked-resources=false
        - --cluster=
        - --kops-ssh-user=admin
        - --env=KUBE_SSH_USER=admin
        - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.16.txt
        - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
        - --extract=release/stable-1.16
        - --ginkgo-parallel
        - --kops-build
        - --kops-priority-path=/home/prow/go/src/k8s.io/kops/kubernetes/platforms/linux/amd64
        - --provider=aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort|In-tree.*Volumes.*\[Driver:.*aws\]
        - --timeout=55m
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: e2e-1-16
  - name: pull-kops-e2e-kubernetes-aws-1-17
    branches:
    - release-1.17
    always_run: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-e2e-platform-aws: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
        imagePullPolicy: Always
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --check-leaked-resources=false
        - --cluster=
        - --kops-ssh-user=admin
        - --env=KUBE_SSH_USER=admin
        - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.17.txt
        - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
        - --extract=release/stable-1.17
        - --ginkgo-parallel
        - --kops-build
        - --kops-priority-path=/home/prow/go/src/k8s.io/kops/kubernetes/platforms/linux/amd64
        - --provider=aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
        - --timeout=55m
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: e2e-1-17
  - name: pull-kops-e2e-kubernetes-aws-1-18
    branches:
    - release-1.18
    always_run: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-e2e-platform-aws: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
        imagePullPolicy: Always
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --check-leaked-resources=false
        - --cluster=
        - --kops-ssh-user=ubuntu
        - --env=KUBE_SSH_USER=ubuntu
        - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.18.txt
        - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
        - --extract=release/stable-1.18
        - --ginkgo-parallel
        - --kops-build
        - --kops-priority-path=/home/prow/go/src/k8s.io/kops/kubernetes/platforms/linux/amd64
        - --provider=aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort
        - --timeout=55m
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: e2e-1-18
  - name: pull-kops-verify-bazel
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-bazel"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-bazel
  - name: pull-kops-verify-generated
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    skip_branches:
    - release-1.17
    - release-1.16
    - release-1.15
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-generate"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-generated
  - name: pull-kops-verify-gomod
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-gomod"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-gomod
  - name: pull-kops-verify-boilerplate
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-boilerplate"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-boilerplate
  - name: pull-kops-verify-gofmt
    always_run: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-gofmt"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-gofmt
  - name: pull-kops-verify-govet
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "govet"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-govet
  - name: pull-kops-verify-packages
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-packages"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-packages
  - name: pull-kops-verify-staticcheck
    branches:
      - master
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-staticcheck"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-staticcheck
  - name: pull-kops-verify-hashes
    skip_report: false
    run_if_changed: '^nodeup\/pkg\/'
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    skip_branches:
    - release-1.17
    - release-1.16
    - release-1.15
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-hashes"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-hashes
  - name: pull-kops-verify-terraform
    skip_report: false
    run_if_changed: '^tests\/integration\/update_cluster\/'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 20m
    path_alias: k8s.io/kops
    skip_branches:
    - release-1.17
    - release-1.16
    - release-1.15
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify-terraform"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-terraform
  - name: pull-kops-verify
    optional: true
    labels:
      preset-dind-enabled: "true"
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 15m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "verify"
        resources:
          requests:
            memory: "2Gi"
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify
periodics:
- interval: 30m
  name: ci-kops-build
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
      args:
      - --repo=k8s.io/kops
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=30
      - --scenario=execute
      - --
      - make
      - gcs-publish-ci
      - GCS_LOCATION=gs://kops-ci/bin
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, kops-presubmits
    testgrid-tab-name: kops-build
    testgrid-alert-email: kubernetes-release-team@googlegroups.com
postsubmits:
  kubernetes/kops:
  - name: kops-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 15m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
        command:
        - runner.sh
        args:
        - "make"
        - "prow-postsubmit"
        - "UPLOAD_DEST=gs://kubernetes-release-dev/kops/ci"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, kops-presubmits
