presubmits:
  kubernetes-sigs/secrets-store-csi-driver:
  - name: pull-secrets-store-csi-driver-lint
    decorate: true
    decoration_config:
      timeout: 10m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - test-style
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-lint
      description: "Run linting rules for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-unit
    decorate: true
    decoration_config:
      timeout: 10m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-unit
      description: "Run unit tests for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-sanity
    decorate: true
    decoration_config:
      timeout: 10m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - sanity-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-sanity
      description: "Run sanity tests for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-e2e-vault
    decorate: true
    decoration_config:
      timeout: 15m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      # this is required because we want to run kind in docker
      preset-dind-enabled: "true"
      # this is required to make CNI installation to succeed for kind
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - >-
          apt-get update && apt-get install bats && apt-get install gettext-base -y &&
          make e2e-bootstrap &&
          make e2e-vault
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-e2e-vault
      description: "Run e2e test with vault provider for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-e2e-azure
    decorate: true
    decoration_config:
      timeout: 15m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      # this is required because we want to run kind in docker
      preset-dind-enabled: "true"
      # this is required to make CNI installation to succeed for kind
      preset-kind-volume-mounts: "true"
      # sets up the azure keyvault parameters used for testing
      preset-azure-secrets-store-creds: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - >-
          apt-get update && apt-get install bats && apt-get install gettext-base -y &&
          make e2e-bootstrap &&
          make e2e-azure
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-e2e-azure
      description: "Run e2e test with azure provider for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-e2e-windows
    decorate: true
    decoration_config:
      timeout: 3h
    always_run: false
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    optional: true
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-azure-windows: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
      preset-azure-secrets-store-creds: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.18
        - --aksengine-location=westus2
        - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
        - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/job-templates/kubernetes_in_tree_volume_plugins.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.48.0/aks-engine-v0.48.0-linux-amd64.tar.gz
        # Specific test args
        - --test-secrets-store-csi-driver
        securityContext:
          privileged: true
        env:
          - name: TEST_WINDOWS
            value: "true"
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-e2e-windows
      description: "Run E2E tests on a Windows cluster for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-build
    decorate: true
    decoration_config:
      timeout: 10m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - >-
          make build build-windows
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-build
      description: "Run make build build-windows for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'

postsubmits:
  kubernetes-sigs/secrets-store-csi-driver:
  - name: secrets-store-csi-driver-e2e-vault-postsubmit
    decorate: true
    decoration_config:
      timeout: 15m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      # this is required because we want to run kind in docker
      preset-dind-enabled: "true"
      # this is required to make CNI installation to succeed for kind
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - >-
          apt-get update && apt-get install bats && apt-get install gettext-base -y &&
          make e2e-bootstrap &&
          make e2e-vault
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver
      testgrid-tab-name: secrets-store-csi-driver-e2e-vault-postsubmit
      description: "Run e2e test with vault provider for Secrets Store CSI driver postsubmit"
      testgrid-num-columns-recent: '30'
  - name: secrets-store-csi-driver-e2e-azure-postsubmit
    decorate: true
    decoration_config:
      timeout: 15m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      # this is required because we want to run kind in docker
      preset-dind-enabled: "true"
      # this is required to make CNI installation to succeed for kind
      preset-kind-volume-mounts: "true"
      # sets up the azure keyvault parameters used for testing
      preset-azure-secrets-store-creds: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - >-
          apt-get update && apt-get install bats && apt-get install gettext-base -y &&
          make e2e-bootstrap &&
          make e2e-azure
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver
      testgrid-tab-name: secrets-store-csi-driver-e2e-azure-postsubmit
      description: "Run e2e test with azure provider for Secrets Store CSI driver postsubmit"
      testgrid-num-columns-recent: '30'
