presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-aks-engine-azure
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - release-1.17
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-agentpoolcount=2
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.17
        - --aksengine-mastervmsize=Standard_DS2_v2
        - --aksengine-agentvmsize=Standard_DS2_v2
        - --aksengine-deploy-custom-k8s
        - --aksengine-location=westus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/Azure/aks-engine/master/examples/kubernetes.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.3/aks-engine-v0.46.3-linux-amd64.tar.gz
        # Specific test args
        - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]
        - --ginkgo-parallel=30
        - --timeout=420m
        securityContext:
          privileged: true
  - name: pull-kubernetes-e2e-azure-disk
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - release-1.17
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes-sigs
      repo: azuredisk-csi-driver
      base_ref: master
      path_alias: sigs.k8s.io/azuredisk-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.17
        - --aksengine-deploy-custom-k8s
        - --aksengine-location=westus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/in-tree.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.3/aks-engine-v0.46.3-linux-amd64.tar.gz
        # Specific test args
        - --test-azure-disk-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: AZURE_STORAGE_DRIVER
          value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
  - name: pull-kubernetes-e2e-azure-disk-vmss
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - release-1.17
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes-sigs
      repo: azuredisk-csi-driver
      base_ref: master
      path_alias: sigs.k8s.io/azuredisk-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.17
        - --aksengine-deploy-custom-k8s
        - --aksengine-location=westus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/in-tree-vmss.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.3/aks-engine-v0.46.3-linux-amd64.tar.gz
        # Specific test args
        - --test-azure-disk-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: AZURE_STORAGE_DRIVER
          value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
        - name: ENABLE_TOPOLOGY
          value: "true"
  - name: pull-kubernetes-e2e-azure-file
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - release-1.17
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes-sigs
      repo: azurefile-csi-driver
      base_ref: master
      path_alias: sigs.k8s.io/azurefile-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-agentpoolcount=2
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.17
        - --aksengine-mastervmsize=Standard_DS2_v2
        - --aksengine-agentvmsize=Standard_DS2_v2
        - --aksengine-deploy-custom-k8s
        - --aksengine-location=westus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/test/e2e/manifest/in-tree.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.48.0/aks-engine-v0.48.0-linux-amd64.tar.gz
        # Specific test args
        - --test-azure-file-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: AZURE_STORAGE_DRIVER
          value: kubernetes.io/azure-file # In-tree Azure file storage class
periodics:
- interval: 24h
  name: kubernetes-e2e-azure-disk-1-17
  decorate: true
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.17
    path_alias: k8s.io/kubernetes
  - org: kubernetes-sigs
    repo: azuredisk-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azuredisk-csi-driver
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.17
      - --aksengine-deploy-custom-k8s
      - --aksengine-location=westus2
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/in-tree.json
      - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.3/aks-engine-v0.46.3-linux-amd64.tar.gz
      # Specific test args
      - --test-azure-disk-csi-driver
      - --ginkgo-parallel=1
      - --timeout=420m
      securityContext:
        privileged: true
      env:
      - name: AZURE_STORAGE_DRIVER
        value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-azure-disk-1-17
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure Disk e2e test with Azure Disk in-tree volume plugin.
    testgrid-num-columns-recent: '30'
- interval: 24h
  name: kubernetes-e2e-azure-disk-vmss-1-17
  decorate: true
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.17
    path_alias: k8s.io/kubernetes
  - org: kubernetes-sigs
    repo: azuredisk-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azuredisk-csi-driver
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.17
      - --aksengine-deploy-custom-k8s
      - --aksengine-location=westus2
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/in-tree-vmss.json
      - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.3/aks-engine-v0.46.3-linux-amd64.tar.gz
      # Specific test args
      - --test-azure-disk-csi-driver
      - --ginkgo-parallel=1
      - --timeout=420m
      securityContext:
        privileged: true
      env:
      - name: AZURE_STORAGE_DRIVER
        value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
      - name: ENABLE_TOPOLOGY
        value: "true"
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-azure-disk-vmss-1-17
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure Disk e2e test on a VMSS-based cluster with Azure Disk in-tree volume plugin.
    testgrid-num-columns-recent: '30'
- interval: 24h
  name: kubernetes-e2e-azure-file-1-17
  decorate: true
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.17
    path_alias: k8s.io/kubernetes
  - org: kubernetes-sigs
    repo: azurefile-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azurefile-csi-driver
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-agentpoolcount=2
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.17
      - --aksengine-mastervmsize=Standard_DS2_v2
      - --aksengine-agentvmsize=Standard_DS2_v2
      - --aksengine-deploy-custom-k8s
      - --aksengine-location=westus2
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/test/e2e/manifest/in-tree.json
      - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.48.0/aks-engine-v0.48.0-linux-amd64.tar.gz
      # Specific test args
      - --test-azure-file-csi-driver
      - --ginkgo-parallel=1
      - --timeout=420m
      securityContext:
        privileged: true
      env:
      - name: AZURE_STORAGE_DRIVER
        value: kubernetes.io/azure-file # In-tree Azure file storage class
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-azure-file-1-17
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure File e2e test with Azure File in-tree volume plugin.
    testgrid-num-columns-recent: '30'
- interval: 24h
  name: kubernetes-e2e-capz-azure-disk-1-17
  decorate: true
  decoration_config:
    timeout: 3h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: master
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  - org: kubernetes-sigs
    repo: azuredisk-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azuredisk-csi-driver
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.17
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
      command:
      - runner.sh
      - ./scripts/ci-entrypoint.sh
      args:
      - bash
      - -c
      - >-
        cd ${GOPATH}/src/sigs.k8s.io/azuredisk-csi-driver &&
        make e2e-test
      env:
      - name: SKIP_UPSTREAM_E2E_TESTS
        value: "true"
      - name: USE_CI_ARTIFACTS
        value: "true"
      - name: AZURE_STORAGE_DRIVER
        value: kubernetes.io/azure-disk # In-tree Azure disk storage class
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-azure-disk-1-17-capz
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure Disk e2e test with Azure Disk in-tree volume plugin on a CAPZ cluster.
    testgrid-num-columns-recent: '30'
- interval: 24h
  name: kubernetes-e2e-capz-azure-disk-vmss-1-17
  decorate: true
  decoration_config:
    timeout: 3h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: master
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  - org: kubernetes-sigs
    repo: azuredisk-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azuredisk-csi-driver
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.17
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
      command:
      - runner.sh
      - ./scripts/ci-entrypoint.sh
      args:
      - bash
      - -c
      - >-
        cd ${GOPATH}/src/sigs.k8s.io/azuredisk-csi-driver &&
        make e2e-test
      env:
      - name: SKIP_UPSTREAM_E2E_TESTS
        value: "true"
      - name: USE_CI_ARTIFACTS
        value: "true"
      - name: EXP_MACHINE_POOL
        value: "true"
      - name: AZURE_STORAGE_DRIVER
        value: kubernetes.io/azure-disk # In-tree Azure disk storage class
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-azure-disk-vmss-1-17-capz
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure Disk e2e test with Azure Disk in-tree volume plugin on a CAPZ cluster with Machine Pool.
    testgrid-num-columns-recent: '30'
- interval: 24h
  name: kubernetes-e2e-capz-azure-file-1-17
  decorate: true
  decoration_config:
    timeout: 3h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: master
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  - org: kubernetes-sigs
    repo: azurefile-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azurefile-csi-driver
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.17
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
      command:
      - runner.sh
      - ./scripts/ci-entrypoint.sh
      args:
      - bash
      - -c
      - >-
        kubectl apply -f templates/addons/azurefile-role.yaml &&
        cd ${GOPATH}/src/sigs.k8s.io/azurefile-csi-driver &&
        make e2e-test
      env:
      - name: SKIP_UPSTREAM_E2E_TESTS
        value: "true"
      - name: USE_CI_ARTIFACTS
        value: "true"
      - name: AZURE_STORAGE_DRIVER
        value: kubernetes.io/azure-file # In-tree Azure file storage class
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-azure-file-1-17-capz
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure File e2e test with Azure File in-tree volume plugin on a CAPZ cluster.
    testgrid-num-columns-recent: '30'
- interval: 24h
  name: kubernetes-e2e-capz-azure-file-vmss-1-17
  decorate: true
  decoration_config:
    timeout: 3h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: master
    path_alias: sigs.k8s.io/cluster-api-provider-azure
  - org: kubernetes-sigs
    repo: azurefile-csi-driver
    base_ref: master
    path_alias: sigs.k8s.io/azurefile-csi-driver
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.17
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
      command:
      - runner.sh
      - ./scripts/ci-entrypoint.sh
      args:
      - bash
      - -c
      - >-
        kubectl apply -f templates/addons/azurefile-role.yaml &&
        cd ${GOPATH}/src/sigs.k8s.io/azurefile-csi-driver &&
        make e2e-test
      env:
      - name: SKIP_UPSTREAM_E2E_TESTS
        value: "true"
      - name: USE_CI_ARTIFACTS
        value: "true"
      - name: EXP_MACHINE_POOL
        value: "true"
      - name: AZURE_STORAGE_DRIVER
        value: kubernetes.io/azure-file # In-tree Azure file storage class
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-azure-file-vmss-1-17-capz
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Run Azure File e2e test with Azure File in-tree volume plugin on a CAPZ cluster with Machine Pool.
    testgrid-num-columns-recent: '30'
