presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-aks-engine-azure
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-agentpoolcount=2
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.18
        - --aksengine-mastervmsize=Standard_DS2_v2
        - --aksengine-agentvmsize=Standard_DS2_v2
        - --aksengine-deploy-custom-k8s
        - --aksengine-location=westus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/Azure/aks-engine/master/examples/kubernetes.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.53.0/aks-engine-v0.53.0-linux-amd64.tar.gz
        # Specific test args
        - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]
        - --ginkgo-parallel=30
        - --timeout=420m
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-upstream, provider-azure-presubmit
      testgrid-tab-name: pr-k8s-e2e-master
      description: Run e2e tests
      testgrid-num-columns-recent: '30'
  - name: pull-kubernetes-e2e-azure-disk
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes-sigs
      repo: azuredisk-csi-driver
      base_ref: master
      path_alias: sigs.k8s.io/azuredisk-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.18
        - --aksengine-deploy-custom-k8s
        - --aksengine-location=westus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/in-tree.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.53.0/aks-engine-v0.53.0-linux-amd64.tar.gz
        # Specific test args
        - --test-azure-disk-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: AZURE_STORAGE_DRIVER
          value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
    annotations:
      testgrid-dashboards: provider-azure-upstream, provider-azure-presubmit
      testgrid-tab-name: pr-k8s-azure-disk-e2e-master
      description: Run Azure Disk e2e test with Azure Disk in-tree volume plugin.
      testgrid-num-columns-recent: '30'
  - name: pull-kubernetes-e2e-azure-disk-vmss
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes-sigs
      repo: azuredisk-csi-driver
      base_ref: master
      path_alias: sigs.k8s.io/azuredisk-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.18
        - --aksengine-deploy-custom-k8s
        - --aksengine-location=westus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/test/e2e/manifest/in-tree-vmss.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.53.0/aks-engine-v0.53.0-linux-amd64.tar.gz
        # Specific test args
        - --test-azure-disk-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: AZURE_STORAGE_DRIVER
          value: "kubernetes.io/azure-disk" # In-tree Azure disk storage class
        - name: ENABLE_TOPOLOGY
          value: "true"
    annotations:
      testgrid-dashboards: provider-azure-upstream, provider-azure-presubmit
      testgrid-tab-name: pr-k8s-azure-disk-e2e-vmss-master
      description: Run Azure Disk e2e test on a VMSS-based availability zone cluster with Azure Disk in-tree volume plugin.
      testgrid-num-columns-recent: '30'
  - name: pull-kubernetes-e2e-azure-file
    decorate: true
    always_run: false
    optional: true
    run_if_changed: 'azure.*\.go'
    path_alias: k8s.io/kubernetes
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes-sigs
      repo: azurefile-csi-driver
      base_ref: master
      path_alias: sigs.k8s.io/azurefile-csi-driver
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-agentpoolcount=2
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.18
        - --aksengine-mastervmsize=Standard_DS2_v2
        - --aksengine-agentvmsize=Standard_DS2_v2
        - --aksengine-deploy-custom-k8s
        - --aksengine-location=westus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/test/e2e/manifest/in-tree.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.53.0/aks-engine-v0.53.0-linux-amd64.tar.gz
        # Specific test args
        - --test-azure-file-csi-driver
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
        env:
        - name: AZURE_STORAGE_DRIVER
          value: kubernetes.io/azure-file # In-tree Azure file storage class
    annotations:
      testgrid-dashboards: provider-azure-upstream, provider-azure-presubmit
      testgrid-tab-name: pr-k8s-azure-file-e2e-master
      description: Run Azure File e2e test with Azure File in-tree volume plugin.
periodics:
- interval: 24h
  name: ci-kubernetes-e2e-aks-engine-conformance-master
  decorate: true
  labels:
    preset-service-account: "true"
    preset-azure-cred: "true"
    preset-dind-enabled: "true"
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      command:
      - runner.sh
      - kubetest
      args:
      # Generic e2e test args
      - --test
      - --up
      - --down
      - --build=quick
      - --dump=$(ARTIFACTS)
      # Azure-specific test args
      - --provider=skeleton
      - --deployment=aksengine
      - --aksengine-agentpoolcount=2
      - --aksengine-admin-username=azureuser
      - --aksengine-creds=$(AZURE_CREDENTIALS)
      - --aksengine-orchestratorRelease=1.18
      - --aksengine-mastervmsize=Standard_DS2_v2
      - --aksengine-agentvmsize=Standard_DS2_v2
      - --aksengine-deploy-custom-k8s
      - --aksengine-location=westus2
      - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
      - --aksengine-template-url=https://raw.githubusercontent.com/Azure/aks-engine/master/examples/kubernetes.json
      - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.53.0/aks-engine-v0.53.0-linux-amd64.tar.gz
      # Specific test args
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]
      - --ginkgo-parallel=30
      - --timeout=420m
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-conformance-master
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Runs conformance & node conformance tests latest kubernetes master with aks-engine
    testgrid-num-columns-recent: '30'
- interval: 24h
  name: ci-kubernetes-e2e-capz-conformance-master
  decorate: true
  decoration_config:
    timeout: 3h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      command:
      - "runner.sh"
      - "./scripts/ci-entrypoint.sh"
      env:
      - name: FOCUS
        value: "\\[Conformance\\]|\\[NodeConformance\\]"
      - name: SKIP
        value: "\\[Slow\\]|\\[Serial\\]|\\[Flaky\\]"
      - name: PARALLEL
        value: "true"
      - name: USE_CI_ARTIFACTS
        value: "true"
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-conformance-master-capz
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Runs conformance & node conformance tests latest kubernetes master with cluster-api-provider-azure
    testgrid-num-columns-recent: '30'
- interval: 24h
  name: ci-kubernetes-e2e-capz-conformance-vmss-master
  decorate: true
  decoration_config:
    timeout: 3h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      command:
      - "runner.sh"
      - "./scripts/ci-entrypoint.sh"
      env:
      - name: FOCUS
        value: "\\[Conformance\\]|\\[NodeConformance\\]"
      - name: SKIP
        value: "\\[Slow\\]|\\[Serial\\]|\\[Flaky\\]"
      - name: PARALLEL
        value: "true"
      - name: USE_CI_ARTIFACTS
        value: "true"
      - name: EXP_MACHINE_POOL
        value: "true"
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 1
          memory: "4Gi"
  annotations:
    testgrid-dashboards: provider-azure-upstream, provider-azure-periodic
    testgrid-tab-name: k8s-e2e-conformance-vmss-master-capz
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com
    description: Runs conformance & node conformance tests latest kubernetes master with cluster-api-provider-azure
    testgrid-num-columns-recent: '30'
