postsubmits:
  # this is the github repo we'll build from; this block needs to be repeated for each repo.
  kubernetes-sigs/k8s-container-image-promoter:
    - name: service-apis-postsubmit-push-to-staging
      cluster: k8s-infra-prow-build-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-network-service-apis
      decorate: true
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200708-4b69e15
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-service-apis
              - --scratch-bucket=gs://k8s-staging-service-apis
              - --env-passthrough=PULL_BASE_REF
              - .
