postsubmits:
  kubernetes-sigs/k8s-container-image-promoter:
    - name: cip-postsubmit-push-to-staging
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-release-releng-blocking
        testgrid-alert-email: k8s-infra-alerts@kubernetes.io, release-managers@kubernetes.io
        testgrid-num-failures-to-alert: '1'
      decorate: true
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200708-4b69e15
            command:
              - /run.sh
            args:
              - --project=k8s-staging-artifact-promoter
              - --scratch-bucket=gs://k8s-staging-artifact-promoter-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
