postsubmits:
  kubernetes-sigs/ingress-controller-conformance:
    - name: post-ingress-conformance-push-echoserver-image
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-network-ingress-controller-conformance
      decorate: true
      run_if_changed: "^images/echoserver/"
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200708-4b69e15
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR
              # images are pushed to.
              - --project=k8s-staging-ingressconformance
              # This is the same as above, but with -gcb appended.
              - --scratch-bucket=gs://k8s-staging-ingressconformance-gcb
              - --env-passthrough=PULL_BASE_REF
              - images/echoserver

    - name: post-ingress-conformance-push-image
      cluster: k8s-infra-prow-build-trusted
      annotations:
        testgrid-dashboards: sig-network-ingress-controller-conformance
      decorate: true
      branches:
        - ^master$
      spec:
        serviceAccountName: gcb-builder
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200708-4b69e15
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR
              # images are pushed to.
              - --project=k8s-staging-ingressconformance
              # This is the same as above, but with -gcb appended.
              - --scratch-bucket=gs://k8s-staging-ingressconformance-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
