presubmits:
  # Check that changes to promoter manifests are valid.
  kubernetes/k8s.io:
  - name: pull-cip-vuln
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
    decorate: true
    skip_report: false
    run_if_changed: 'k8s.gcr.io/((images/.*/images\.yaml)|(manifests/.*/promoter-manifest\.yaml))'
    max_concurrency: 10
    branches:
    - ^master$
    spec:
      serviceAccountName: k8s-infra-gcr-promoter-scanning
      containers:
      - image: us.gcr.io/k8s-artifacts-prod/artifact-promoter/cip:20200328-v2.3.1-172-gfeb5dc0
        command:
        - cip
        args:
        # Pod Utilities already sets pwd to
        # /home/prow/go/src/github.com/{{.Org}}/{{.Repo}}, so just '.' should
        # suffice, but it's nice to be explicit.
        - -thin-manifest-dir=/home/prow/go/src/github.com/kubernetes/k8s.io/k8s.gcr.io
        - -use-service-account
  - name: pull-k8sio-cip
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
    decorate: true
    skip_report: false
    run_if_changed: 'k8s.gcr.io/((images/.*/images\.yaml)|(manifests/.*/promoter-manifest\.yaml))'
    max_concurrency: 10
    branches:
    - ^master$
    spec:
      containers:
      - image: us.gcr.io/k8s-artifacts-prod/artifact-promoter/cip:20200328-v2.3.1-172-gfeb5dc0
        command:
        - cip
        args:
        # Pod Utilities already sets pwd to
        # /home/prow/go/src/github.com/{{.Org}}/{{.Repo}}, so just '.' should
        # suffice, but it's nice to be explicit.
        - -thin-manifest-dir=/home/prow/go/src/github.com/kubernetes/k8s.io/k8s.gcr.io
  # Check that changes to backup scripts are valid.
  - name: pull-k8sio-backup
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: wg-k8s-infra-k8sio
    decorate: true
    run_if_changed: '^infra/gcp/backup_tools/'
    max_concurrency: 1
    branches:
    - ^master$
    spec:
      serviceAccountName: k8s-infra-gcr-promoter-test
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200623-2424179-1.17
        command:
        - infra/gcp/backup_tools/backup_test.sh
        env:
        # Even though GOPATH is set to /go in the kubekins-e2e image, we set it
        # here anyway in case the underlying image changes (the backup_test.sh
        # script needs it to be defined).
        - name: GOPATH
          value: /go
  kubernetes-sigs/k8s-container-image-promoter:
  # Run promoter e2e tests.
  - name: pull-cip-e2e
    decorate: true
    path_alias: "sigs.k8s.io/k8s-container-image-promoter"
    skip_report: false
    always_run: true
    # Because we run e2e tests, we cannot run more than 1 instance at a time
    # (the e2e test resources are not isolated across test runs).
    max_concurrency: 1
    branches:
    - ^master$
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200623-2424179-master
        command:
        - "./test-e2e/cip/e2e-entrypoint-from-container.sh"
        env:
        - name: CIP_E2E_KEY_FILE
          value: "/etc/k8s-cip-test-prod-service-account/service-account.json"
        volumeMounts:
        - name: k8s-cip-test-prod-service-account-creds
          mountPath: /etc/k8s-cip-test-prod-service-account
          readOnly: true
      volumes:
      - name: k8s-cip-test-prod-service-account-creds
        secret:
          secretName: k8s-cip-test-prod-service-account
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
  - name: pull-cip-auditor-e2e
    decorate: true
    path_alias: "sigs.k8s.io/k8s-container-image-promoter"
    skip_report: false
    always_run: true
    # Because we run e2e tests, we cannot run more than 1 instance at a time
    # (the e2e test resources are not isolated across test runs).
    max_concurrency: 1
    branches:
    - ^master$
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200623-2424179-master
        command:
        - "./test-e2e/cip-auditor/entrypoint-from-container.sh"
        env:
        - name: CIP_E2E_KEY_FILE
          value: "/etc/k8s-gcr-audit-test-prod-service-account/service-account.json"
        volumeMounts:
        - name: k8s-gcr-audit-test-prod-service-account-creds
          mountPath: /etc/k8s-gcr-audit-test-prod-service-account
          readOnly: true
      volumes:
      - name: k8s-gcr-audit-test-prod-service-account-creds
        secret:
          secretName: k8s-gcr-audit-test-prod-service-account
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
  # Build all binaries and also run unit tests.
  - name: pull-cip-unit-tests
    decorate: true
    path_alias: "sigs.k8s.io/k8s-container-image-promoter"
    skip_report: false
    always_run: true
    branches:
    - ^master$
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200623-2424179-master
        command:
        - "make"
        args:
        - "test-ci"
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
  # Run linter.
  - name: pull-cip-lint
    decorate: true
    path_alias: "sigs.k8s.io/k8s-container-image-promoter"
    skip_report: false
    always_run: true
    branches:
    - ^master$
    spec:
      containers:
      - image: golangci/golangci-lint:latest
        command:
        - "make"
        args:
        - "lint-ci"
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
