presubmits:
  kubernetes-sigs/ingress-controller-conformance:

  - name: pull-ingress-controller-conformance-boilerplate
    always_run: true
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: sigs.k8s.io/ingress-controller-conformance
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - ./hack/verify-boilerplate.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-controller-conformance
      testgrid-tab-name: boilerplate

  - name: pull-ingress-controller-conformance-codegen
    always_run: true
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: sigs.k8s.io/ingress-controller-conformance
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - verify-codegen
    annotations:
      testgrid-dashboards: sig-network-ingress-controller-conformance
      testgrid-tab-name: verify-codegen

  - name: pull-ingress-controller-conformance-gofmt
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/ingress-controller-conformance
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - ./hack/verify-gofmt.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-controller-conformance
      testgrid-tab-name: gofmt

  - name: pull-ingress-controller-conformance-golint
    always_run: true
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: sigs.k8s.io/ingress-controller-conformance
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - ./hack/verify-golint.sh
    annotations:
      testgrid-dashboards: sig-network-ingress-controller-conformance
      testgrid-tab-name: golint

  - name: pull-ingress-controller-conformance-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: sigs.k8s.io/ingress-controller-conformance
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - build
    annotations:
      testgrid-dashboards: sig-network-ingress-controller-conformance
      testgrid-tab-name: build
