periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gce-ha-master
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=240
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --env=MULTIZONE=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-project=kubernetes-ha-master
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:HAMaster\] --minStartupPods=8
      - --timeout=220m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master

  annotations:
    testgrid-dashboards: google-gce
    testgrid-tab-name: gce-ha-master
