# periodic jobs

periodics:
- name: ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-19-master
  interval: 2h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kubeadm,sig-release-master-informing
    testgrid-tab-name: kubeadm-kinder-upgrade-1-19-master
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle+testgrid@googlegroups.com, kubernetes-release-team@googlegroups.com
    description: "OWNER: sig-cluster-lifecycle (kinder); Uses kubeadm/kinder to create a cluster, upgrade it and run kubeadm-e2e and the conformance suite"
    testgrid-num-columns-recent: "20"
    testgrid-num-failures-to-alert: "8"
    testgrid-alert-stale-results-hours: "16"
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      command:
      - runner.sh
      - "../kubeadm/kinder/ci/kinder-run.sh"
      args:
      - "upgrade-1.19-master"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "9000Mi"
          cpu: 2000m

- name: ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-1-19
  interval: 12h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kubeadm,sig-release-1.19-informing
    testgrid-tab-name: kubeadm-kinder-upgrade-1-18-1-19
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle+testgrid@googlegroups.com, kubernetes-release-team@googlegroups.com
    description: "OWNER: sig-cluster-lifecycle (kinder); Uses kubeadm/kinder to create a cluster, upgrade it and run kubeadm-e2e and the conformance suite"
    testgrid-num-columns-recent: "20"
    testgrid-num-failures-to-alert: "4"
    testgrid-alert-stale-results-hours: "48"
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.19
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.19
      command:
      - runner.sh
      - "../kubeadm/kinder/ci/kinder-run.sh"
      args:
      - "upgrade-1.18-1.19"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "9000Mi"
          cpu: 2000m

- name: ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-17-1-18
  interval: 12h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kubeadm,sig-release-1.18-informing
    testgrid-tab-name: kubeadm-kinder-upgrade-1-17-1-18
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle+testgrid@googlegroups.com, kubernetes-release-team@googlegroups.com
    description: "OWNER: sig-cluster-lifecycle (kinder); Uses kubeadm/kinder to create a cluster, upgrade it and run kubeadm-e2e and the conformance suite"
    testgrid-num-columns-recent: "20"
    testgrid-num-failures-to-alert: "4"
    testgrid-alert-stale-results-hours: "48"
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.18
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.18
      command:
      - runner.sh
      - "../kubeadm/kinder/ci/kinder-run.sh"
      args:
      - "upgrade-1.17-1.18"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "9000Mi"
          cpu: 2000m

- name: ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-16-1-17
  interval: 12h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kubeadm,sig-release-1.17-informing
    testgrid-tab-name: kubeadm-kinder-upgrade-1-16-1-17
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle+testgrid@googlegroups.com, kubernetes-release-team@googlegroups.com
    description: "OWNER: sig-cluster-lifecycle (kinder); Uses kubeadm/kinder to create a cluster, upgrade it and run kubeadm-e2e and the conformance suite"
    testgrid-num-columns-recent: "20"
    testgrid-num-failures-to-alert: "4"
    testgrid-alert-stale-results-hours: "48"
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.17
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.17
      command:
      - runner.sh
      - "../kubeadm/kinder/ci/kinder-run.sh"
      args:
      - "upgrade-1.16-1.17"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "9000Mi"
          cpu: 2000m

- name: ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-15-1-16
  interval: 12h
  decorate: true
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kubeadm,sig-release-1.16-informing
    testgrid-tab-name: kubeadm-kinder-upgrade-1-15-1-16
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle+testgrid@googlegroups.com, kubernetes-release-team@googlegroups.com
    description: "OWNER: sig-cluster-lifecycle (kinder); Uses kubeadm/kinder to create a cluster, upgrade it and run kubeadm-e2e and the conformance suite"
    testgrid-num-columns-recent: "20"
    testgrid-num-failures-to-alert: "4"
    testgrid-alert-stale-results-hours: "48"
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.16
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: kubeadm
    base_ref: master
    path_alias: k8s.io/kubeadm
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.16
      command:
      - runner.sh
      - "../kubeadm/kinder/ci/kinder-run.sh"
      args:
      - "upgrade-1.15-1.16"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "9000Mi"
          cpu: 2000m
