---
images:
  cosstable2-resource1:
    image: cos-77-12371-274-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 0 pods per node \[Benchmark\]'
  cosstable2-resource2:
    image: cos-77-12371-274-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 35 pods per node \[Benchmark\]'
  cosstable2-resource3:
    image: cos-77-12371-274-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 90 pods per node \[Benchmark\]'

  cosstable2-density1:
    image: cos-77-12371-274-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 35 pods with 0s? interval \[Benchmark\]'
  cosstable2-density2:
    image: cos-77-12371-274-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 90 pods with 0s? interval \[Benchmark\]'
  cosstable2-density2-qps60:
    image: cos-77-12371-274-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 90 pods with 0s? interval \(QPS 60\) \[Benchmark\]'
  cosstable2-density3:
    image: cos-77-12371-274-0
    project: cos-cloud
    machine: n1-standard-2
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 90 pods with 0s? interval \[Benchmark\]'
  cosstable2-density4:
    image: cos-77-12371-274-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 90 pods with 100ms interval \[Benchmark\]'

  cosstable1-resource1:
    image: cos-stable-81-12871-103-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 0 pods per node \[Benchmark\]'
  cosstable1-resource2:
    image: cos-stable-81-12871-103-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 35 pods per node \[Benchmark\]'
  cosstable1-resource3:
    image: cos-stable-81-12871-103-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 90 pods per node \[Benchmark\]'
  cosbeta-resource1:
    image: cos-beta-81-12871-44-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 0 pods per node \[Benchmark\]'
  cosbeta-resource2:
    image: cos-beta-81-12871-44-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 35 pods per node \[Benchmark\]'
  cosbeta-resource3:
    image: cos-beta-81-12871-44-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 90 pods per node \[Benchmark\]'

  cosbeta-density1:
    image: cos-beta-81-12871-44-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 35 pods with 0s? interval \[Benchmark\]'
  cosbeta-density2:
    image: cos-beta-81-12871-44-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 90 pods with 0s? interval \[Benchmark\]'
  cosbeta-density2-qps60:
    image: cos-beta-81-12871-44-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 90 pods with 0s? interval \(QPS 60\) \[Benchmark\]'
  cosbeta-density3:
    image: cos-beta-81-12871-44-0
    project: cos-cloud
    machine: n1-standard-2
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 90 pods with 0s? interval \[Benchmark\]'
  cosbeta-density4:
    image: cos-beta-81-12871-44-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'create 90 pods with 100ms interval \[Benchmark\]'

  cosdev-resource1:
    image: cos-dev-83-13020-12-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 0 pods per node \[Benchmark\]'
  cosdev-resource2:
    image: cos-dev-83-13020-12-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 35 pods per node \[Benchmark\]'
  cosdev-resource3:
    image: cos-dev-83-13020-12-0
    project: cos-cloud
    machine: n1-standard-1
    metadata: "user-data<test/e2e_node/jenkins/gci-init.yaml,gci-update-strategy=update_disabled"
    tests:
      - 'resource tracking for 90 pods per node \[Benchmark\]'

  # NOTE: recommended versions of the ubuntu-gke images for GKE 1.14, 1.15 and 1.16 clusters
  # were taken from https://cloud.google.com/kubernetes-engine/docs/release-notes
  ubuntustable1-resource1:
    image: ubuntu-gke-1804-1-16-v20200330
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 0 pods per node \[Benchmark\]'
  ubuntustable1-resource2:
    image: ubuntu-gke-1804-1-16-v20200330
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 35 pods per node \[Benchmark\]'
  ubuntustable1-resource3:
    image: ubuntu-gke-1804-1-16-v20200330
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 90 pods per node \[Benchmark\]'

  ubuntustable2-resource1:
    image: ubuntu-gke-1804-1-15-v20200330
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 0 pods per node \[Benchmark\]'
  ubuntustable2-resource2:
    image: ubuntu-gke-1804-1-15-v20200330
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 35 pods per node \[Benchmark\]'
  ubuntustable2-resource3:
    image: ubuntu-gke-1804-1-15-v20200330
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 90 pods per node \[Benchmark\]'

  ubuntustable3-resource1:
    image: ubuntu-gke-1804-1-14-v20200219
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 0 pods per node \[Benchmark\]'
  ubuntustable3-resource2:
    image: ubuntu-gke-1804-1-14-v20200219
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 35 pods per node \[Benchmark\]'
  ubuntustable3-resource3:
    image: ubuntu-gke-1804-1-14-v20200219
    project: ubuntu-os-gke-cloud
    machine: n1-standard-1
    tests:
      - 'resource tracking for 90 pods per node \[Benchmark\]'
