periodics:
- name: ci-build-and-push-k8s-at-golang-tip
  interval: 8h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    testgrid-dashboards: sig-scalability-golang
    testgrid-tab-name: build-and-push-k8s-at-golang-tip
  spec:
    containers:
      - image: gcr.io/k8s-testimages/bootstrap:v20200430-be2a8a9
        args:
        - --root=/go/src
        - --repo=k8s.io/perf-tests=master
        - --timeout=75
        - --scenario=execute
        - --
        - make
        - --
        - --directory=/go/src/k8s.io/perf-tests/golang
        - K8S_COMMIT=e97c570a4ba5ba1e2285d3278396937feaa15385 # head of release-1.18 branch as of 2020-04-28
        - K8S_RELEASE_COMMIT=5ad08a0987f35d7b7280e847078987f58c6f8e1f # head of master branch as of 2020-05-04
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true

- interval: 8h
  name: ci-golang-tip-k8s-1-18
  cluster: scalability
  tags:
  - "perfDashPrefix: golang-tip-k8s-1-18"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-dind-enabled: "true"
    preset-e2e-kubemark-common: "true"
    preset-e2e-kubemark-gce-scale: "true"
  annotations:
    testgrid-alert-email: go-kubernetes-scalability-tickets@googlegroups.com
    testgrid-dashboards: sig-scalability-golang
    testgrid-num-failures-to-alert: "2"
    testgrid-tab-name: golang-tip-k8s-1-18
  spec:
    containers:
    - args:
      - --timeout=460
      # head of perf-tests' master as of 2020-05-29
      - --repo=k8s.io/perf-tests=master:c8e93e287413fb0efec4478e2f47f1e7b1a92bfd
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-golang
      - --env=CL2_ENABLE_PVS=false
      - --env=CL2_LOAD_TEST_THROUGHPUT=50
      - --env=KUBEMARK_CONTROLLER_MANAGER_TEST_ARGS=--profiling --kube-api-qps=200 --kube-api-burst=200
      - --env=KUBEMARK_SCHEDULER_TEST_ARGS=--profiling --kube-api-qps=200 --kube-api-burst=200
      - --extract=gs://k8s-scale-golang-build/ci/latest-1.18.txt
      - --gcp-node-size=n1-standard-8
      - --gcp-nodes=50
      - --gcp-project=k8s-presubmit-scale
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --kubemark
      - --kubemark-nodes=2500
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
      - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=${JOB_NAME}-${BUILD_ID}
      - --test-cmd-args=--nodes=2500
      - --test-cmd-args=--provider=kubemark
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/enable_prometheus_api_responsiveness.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/ignore_known_kubemark_container_restarts.yaml
      - --test-cmd-args=--testoverrides=./testing/overrides/5000_nodes.yaml
      - --test-cmd-args=--testoverrides=./testing/load/golang/custom_api_call_thresholds.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=430m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      env:
      - name: CL2_ENABLE_VIOLATIONS_FOR_API_CALL_PROMETHEUS
        value: "true"
      # docker-in-docker needs privilged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 6
          memory: "16Gi"

# Oneoff jobs for full (5k gce) golang tests
# TODO(mm4tt): Clean them up
- cron: '0 0 2 5 *' # Run at 00:00 UTC on May 2nd (Saturday)
  name: ci-golang-1-14-2-k8s-1-18-full
  cluster: scalability
  tags:
  - "perfDashPrefix: golang-1-14-2-k8s-1-18-full"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  annotations:
    testgrid-dashboards: sig-scalability-golang
    testgrid-tab-name: golang-1-14-2-k8s-1-18-full
  spec:
    containers:
    - args:
      - --timeout=1080
      # head of perf-test's master as of 2020-04-28
      - --repo=k8s.io/perf-tests=master:2a5b685c253ca0b88589d61b5d2c57ff548347e8
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-scale-cluster
      - --env=HEAPSTER_MACHINE_TYPE=n1-standard-32
      - --env=KUBE_DNS_MEMORY_LIMIT=300Mi
      - --extract=gs://kubernetes-release-dev/devel/v1.18.3-beta.0.5+d5282c1b0604f4
      - --gcp-nodes=5000
      - --gcp-project=k8s-scale-testing
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
      - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=${JOB_NAME}-${BUILD_ID}
      - --test-cmd-args=--nodes=5000
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testconfig=testing/access-tokens/config.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/enable_prometheus_api_responsiveness.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/ignore_known_gce_container_restarts.yaml
      - --test-cmd-args=--testoverrides=./testing/overrides/5000_nodes.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=1050m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      resources:
        requests:
          cpu: 6
          memory: "16Gi"
- cron: '0 0 6 5 *' # Run at 00:00 UTC on May 6th (Wednesday)
  name: ci-golang-tip-k8s-1-18-full
  cluster: scalability
  tags:
  - "perfDashPrefix: golang-tip-k8s-1-18-full"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  annotations:
    testgrid-dashboards: sig-scalability-golang
    testgrid-tab-name: golang-tip-k8s-1-18-full
  spec:
    containers:
    - args:
      - --timeout=1080
      # head of perf-test's master as of 2020-04-28
      - --repo=k8s.io/perf-tests=master:2a5b685c253ca0b88589d61b5d2c57ff548347e8
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-scale-cluster
      - --env=HEAPSTER_MACHINE_TYPE=n1-standard-32
      - --env=KUBE_DNS_MEMORY_LIMIT=300Mi
      - --extract=gs://k8s-scale-golang-build/ci/latest-1.18.txt
      - --gcp-nodes=5000
      - --gcp-project=k8s-scale-testing
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
      - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=${JOB_NAME}-${BUILD_ID}
      - --test-cmd-args=--nodes=5000
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testconfig=testing/access-tokens/config.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/enable_prometheus_api_responsiveness.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/ignore_known_gce_container_restarts.yaml
      - --test-cmd-args=--testoverrides=./testing/overrides/5000_nodes.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=1050m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      resources:
        requests:
          cpu: 6
          memory: "16Gi"
