periodics:
- name: ci-kubernetes-storage-scalability
  tags:
    - "perfDashPrefix: storage"
    - "perfDashJobType: storage"
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-node: "true"
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: storage
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      args:
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --timeout=360
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-nodes=1
      - --provider=gce
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--nodes=1
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testsuite=testing/experimental/storage/pod-startup/suite.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=300m
      - --use-logexporter

- interval: 6h
  name: ci-kubernetes-e2e-gci-gce-scalability-networkpolicies
  tags:
    - "perfDashPrefix: networkpolicies"
    - "perfDashJobType: networkpolicies"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: calico
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      env:
      - name: NETWORK_POLICY_PROVIDER
        value: "calico"
      - name: ADDITIONAL_MACHINE_TYPE
        value: "n1-standard-2"
      - name: NUM_ADDITIONAL_NODES
        value: "4"
      args:
      - --timeout=140
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/perf-tests=master
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=e2e-scalability-calico
      - --env=CL2_ENABLE_NETWORKPOLICIES=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-nodes=100
      - --gcp-project-type=scalability-project
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --env=CL2_ENABLE_CLUSTER_OOMS_TRACKER=true
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
      - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gci-gce-scalability-np-${BUILD_ID}
      - --test-cmd-args=--nodes=100
      - --test-cmd-args=--prometheus-scrape-node-exporter
      - --test-cmd-args=--provider=gce
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/density/config.yaml
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/use_simple_latency_query.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=120m
      - --use-logexporter

- interval: 6h
  name: ci-kubernetes-e2e-scalability-experimental-load
  tags:
    - "perfDashPrefix: gce-100Nodes-master-experimental"
    - "perfDashJobType: performance"
    - "perfDashBuildsCount: 500"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: experimental-load
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        args:
          - --timeout=140
          - --repo=k8s.io/kubernetes=master
          - --repo=k8s.io/perf-tests=master
          - --root=/go/src
          - --scenario=kubernetes_e2e
          - --
          - --check-leaked-resources
          # TODO(oxddr): remove once debugging is finished
          - --env=KUBEPROXY_TEST_LOG_LEVEL=--v=4
          - --cluster=e2e-big-load
          - --extract=ci/latest
          - --gcp-node-image=gci
          - --gcp-nodes=100
          - --gcp-project-type=scalability-project
          - --gcp-zone=us-east1-b
          - --provider=gce
          - --test=false
          - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
          - --test-cmd-args=cluster-loader2
          - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
          - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=${JOB_NAME}-${BUILD_ID}
          - --test-cmd-args=--nodes=100
          - --test-cmd-args=--prometheus-scrape-node-exporter
          - --test-cmd-args=--provider=gce
          - --test-cmd-args=--report-dir=/workspace/_artifacts
          - --test-cmd-args=--testconfig=testing/load/experimental-config.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/enable_prometheus_api_responsiveness.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/use_simple_latency_query.yaml
          - --test-cmd-args=--testoverrides=./testing/overrides/load_throughput.yaml
          - --test-cmd-name=ClusterLoaderV2
          - --timeout=120m
          - --use-logexporter

- interval: 1h
  name: ci-kubernetes-e2e-scalability-experimental-load-containerd
  tags:
    - "perfDashPrefix: gce-100Nodes-master-experimental-containerd"
    - "perfDashJobType: performance"
    - "perfDashBuildsCount: 500"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
    preset-e2e-scalability-containerd: "true"
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: experimental-load-containerd
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        args:
          - --timeout=140
          - --repo=k8s.io/kubernetes=master
          - --repo=k8s.io/perf-tests=master
          - --root=/go/src
          - --scenario=kubernetes_e2e
          - --
          - --check-leaked-resources
          - --cluster=e2e-big-load-containerd
          # TODO(oxddr): remove once debugging is finished
          - --env=KUBEPROXY_TEST_LOG_LEVEL=--v=4
          - --extract=ci/latest
          - --gcp-node-image=gci
          - --gcp-nodes=100
          - --gcp-project-type=scalability-project
          - --gcp-zone=us-east1-b
          - --provider=gce
          - --test=false
          - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
          - --test-cmd-args=cluster-loader2
          - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
          - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=${JOB_NAME}-${BUILD_ID}
          - --test-cmd-args=--nodes=100
          - --test-cmd-args=--prometheus-scrape-node-exporter
          - --test-cmd-args=--provider=gce
          - --test-cmd-args=--report-dir=/workspace/_artifacts
          - --test-cmd-args=--testconfig=testing/load/experimental-config.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/enable_prometheus_api_responsiveness.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/use_simple_latency_query.yaml
          - --test-cmd-args=--testoverrides=./testing/overrides/load_throughput.yaml
          - --test-cmd-name=ClusterLoaderV2
          - --timeout=120m
          - --use-logexporter

  # Experimental job providing visibility into state of containerd.
- interval: 6h
  name: ci-kubernetes-e2e-gci-gce-scalability-containerd-correctness
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
    preset-e2e-scalability-containerd: "true"
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: gce-cos-master-scalability-100-containerd-correctness
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        args:
          - --repo=k8s.io/kubernetes=master
          - --root=/go/src
          - --scenario=kubernetes_e2e
          - --timeout=270
          - --
          - --check-leaked-resources
          - --cluster=e2e-containerd-conformance
          - --extract=ci/latest
          - --gcp-node-image=gci
          - --gcp-nodes=100
          - --gcp-project-type=scalability-project
          - --gcp-ssh-proxy-instance-name=e2e-containerd-conformance-master
          - --gcp-zone=us-east1-b
          - --provider=gce
          - --test=true
          - --ginkgo-parallel=40
          - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[DisabledForLargeClusters\] --minStartupPods=8 --node-schedulable-timeout=90m
          - --timeout=240m
          - --use-logexporter
        resources:
          requests:
            cpu: 2
            memory: "6Gi"

  # Experimental job confirming that node killer works. Fork of ci-kubernetes-e2e-gci-gce-scalability.
  # To be removed after Chaos Monkey flags are enabled in ci-kubernetes-e2e-gci-gce-scalability
- interval: 6h
  name: ci-kubernetes-e2e-gci-gce-scalability-node-killer
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-scalability-common: "true"
  annotations:
    testgrid-dashboards: sig-scalability-experiments
    testgrid-tab-name: gce-cos-master-scalability-100-nodekiller
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        args:
          - --timeout=140
          - --repo=k8s.io/kubernetes=master
          - --repo=k8s.io/perf-tests=master
          - --root=/go/src
          - --scenario=kubernetes_e2e
          - --
          - --check-leaked-resources
          # TODO(oxddr): remove once debugging is finished
          - --env=KUBEPROXY_TEST_LOG_LEVEL=--v=4
          - --cluster=e2e-big
          - --extract=ci/latest
          - --gcp-node-image=gci
          - --gcp-nodes=100
          - --gcp-project-type=scalability-project
          - --gcp-zone=us-east1-b
          - --provider=gce
          - --env=CL2_ENABLE_CLUSTER_OOMS_TRACKER=true
          - --test=false
          - --test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh
          - --test-cmd-args=cluster-loader2
          - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
          - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=${JOB_NAME}-${BUILD_ID}
          - --test-cmd-args=--nodes=100
          - --test-cmd-args=--prometheus-scrape-node-exporter
          - --test-cmd-args=--provider=gce
          - --test-cmd-args=--report-dir=/workspace/_artifacts
          - --test-cmd-args=--testconfig=testing/load/config.yaml
          - --test-cmd-args=--testoverrides=./testing/chaosmonkey/override.yaml
          - --test-cmd-args=--testoverrides=./testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/enable_prometheus_api_responsiveness.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml
          - --test-cmd-args=--testoverrides=./testing/experiments/use_simple_latency_query.yaml
          - --test-cmd-args=--testoverrides=./testing/overrides/load_throughput.yaml
          - --test-cmd-name=ClusterLoaderV2
          - --timeout=120m
          - --use-logexporter
