presubmits:
  kubernetes-sigs/cluster-api:
  - name: pull-cluster-api-build
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-service-account: "true"
    skip_branches:
    - gh-pages
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.18
        command:
        - runner.sh
        - ./scripts/ci-build.sh
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: pr-build
  - name: pull-cluster-api-make
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    skip_branches:
    - gh-pages
    spec:
      containers:
      - command:
        - runner.sh
        - ./scripts/ci-make.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.18
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: pr-make
  - name: pull-cluster-api-apidiff
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    optional: true
    labels:
      preset-service-account: "true"
    skip_branches:
    - gh-pages
    - release-0.2
    spec:
      containers:
      - command:
        - runner.sh
        - ./scripts/ci-apidiff.sh
        image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.18
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: pr-apidiff
  - name: pull-cluster-api-verify
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-service-account: "true"
    skip_branches:
    - gh-pages
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.18
        command:
        - "runner.sh"
        - "make"
        - "verify"
        resources:
          requests:
            cpu: "6000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: pr-verify
  - name: pull-cluster-api-test
    decorate: true
    path_alias: sigs.k8s.io/cluster-api
    always_run: true
    labels:
      preset-service-account: "true"
    skip_branches:
    - gh-pages
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.18
        args:
        - runner.sh
        - ./scripts/ci-test.sh
        resources:
          requests:
            cpu: "6000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: pr-test
  - name: pull-cluster-api-e2e
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    skip_branches:
      - gh-pages
      - release-0.2
    path_alias: sigs.k8s.io/cluster-api
    optional: true
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-1.18
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "6000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api
      testgrid-tab-name: pr-e2e
