#******************************************************************************
# kubeflow/kfctl
#******************************************************************************
# These tests are named kubeflow even though they are for the kfctl repo
# because that used to be the repo that had our main E2E tests for kubeflow
periodics:
- name: kubeflow-periodic-1-1
  cluster: kubeflow
  interval: 8h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: kfctl
      - name: BRANCH_NAME
        value: v1.1-branch
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow on the 1-0 release
- name: kubeflow-periodic-1-0
  cluster: kubeflow
  interval: 4h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: kfctl
      - name: BRANCH_NAME
        value: v1.0-branch
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow on the 1-0 release
- name: kubeflow-periodic-0-7
  cluster: kubeflow
  # Might want to increase this after the 0.7 release is done.
  # Other periodics run at 8h.
  interval: 4h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: kfctl
      - name: BRANCH_NAME
        value: v0.7-branch
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow on the 0-7 release
#******************************************************************************
# kubeflow/kubeflow
#******************************************************************************
- name: kubeflow-periodic-master
  cluster: kubeflow
  interval: 4h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: kubeflow
      - name: BRANCH_NAME
        value: master
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow on the latest master branch.
    # TODO: use a public email group
    testgrid-alert-email: kubeflow-engineering@google.com
    testgrid-num-failures-to-alert: "3"

- name: kubeflow-kubeflow-periodic-1-1
  cluster: kubeflow
  interval: 8h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: kfctl
      - name: BRANCH_NAME
        value: v1.1-branch
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow on the 1-1 branch

#******************************************************************************
# kubeflow/gcp-blueprints
#******************************************************************************
# Periodic tests currently aren't deploying infrastructure; they are
# just running against the auto deployed clusters so we can run them
# fairly frequently.
- name: kubeflow-gcp-blueprints-periodic-master
  cluster: kubeflow
  interval: 20m
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: gcp-blueprints
      - name: BRANCH_NAME
        value: master
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow gcp blueprints on the latest master branch.
    # TODO: use a public email group
    testgrid-alert-email: kubeflow-engineering@google.com
    testgrid-num-failures-to-alert: "3"
- name: kubeflow-gcp-blueprints-periodic-1-1
  cluster: kubeflow
  interval: 20m
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: gcp-blueprints
      - name: BRANCH_NAME
        value: v1.1-branch
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow gcp blueprints on the 1.1 branch.
    # TODO: use a public email group
    testgrid-alert-email: kubeflow-engineering@google.com
    testgrid-num-failures-to-alert: "3"
#******************************************************************************
# kubeflow/manifests
#******************************************************************************
- name: kubeflow-manifests-periodic-1-1
  cluster: kubeflow
  interval: 8h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: manifests
      - name: BRANCH_NAME
        value: v1.1-branch
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow/manifests on the master branch.
- name: kubeflow-manifests-periodic-master
  cluster: kubeflow
  interval: 8h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: manifests
      - name: BRANCH_NAME
        value: master
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow/manifests on the master branch.
#******************************************************************************
# kubeflow/examples
#******************************************************************************
- name: kubeflow-examples-periodic
  cluster: kubeflow
  interval: 1h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: examples
      - name: BRANCH_NAME
        value: master
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow examples
#******************************************************************************
# kubeflow/kfctl
#******************************************************************************
- name: kubeflow-kfctl-periodic
  cluster: kubeflow
  interval: 8h
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/kubeflow-ci/test-worker:latest
      imagePullPolicy: Always
      env:
      - name: REPO_OWNER
        value: kubeflow
      - name: REPO_NAME
        value: kfctl
      - name: BRANCH_NAME
        value: master
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic testing of Kubeflow kfctl
- name: kubeflow-periodic-project-cleanup
  cluster: kubeflow
  interval: 1h
  decorate: true
  labels:
    preset-service-account: "true"
  extra_refs:
  - org: kubeflow
    repo: pipelines
    base_ref: master
    workdir: true
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        imagePullPolicy: Always
        command:
        - "./test/tools/project-cleaner/project_cleaner.sh"
        env:
          - name: REPO_OWNER
            value: kubeflow
          - name: REPO_NAME
            value: kubeflow
          - name: BRANCH_NAME
            value: master
  annotations:
    testgrid-dashboards: sig-big-data
    description: Periodic job to cleanup ml-pipeline-test GCP project
