presubmits:
  kubernetes-sigs/blobfuse-csi-driver:
  - name: pull-blobfuse-csi-driver-verify
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/blobfuse-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - verify
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-blobfuse-csi-driver-verify
      description: "Run code verification tests for Blobfuse CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blobfuse-csi-driver-unit
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/blobfuse-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - unit-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-blobfuse-csi-driver-unit
      description: "Run unit tests for Blobfuse CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blobfuse-csi-driver-sanity
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/blobfuse-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - sanity-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-blobfuse-csi-driver-sanity
      description: "Run sanity tests for Blobfuse CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blobfuse-csi-driver-integration
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/blobfuse-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - make
        - integration-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-blobfuse-csi-driver-integration
      description: "Run integration tests for Blobfuse CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blobfuse-csi-driver-e2e
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/blobfuse-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.17
        - --aksengine-location=eastus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/blobfuse-csi-driver/master/test/manifest/linux.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.0/aks-engine-v0.46.0-linux-amd64.tar.gz
        - --test-blobfuse-csi-driver
        # Specific test args
        - --ginkgo-parallel=1
        - --timeout=420m
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-blobfuse-csi-driver-e2e
      description: "Run E2E tests for Blobfuse CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-blobfuse-csi-driver-e2e-vmss
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/blobfuse-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.17
        - --aksengine-location=eastus2
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/blobfuse-csi-driver/master/test/manifest/linux-vmss.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/v0.46.0/aks-engine-v0.46.0-linux-amd64.tar.gz
        # Specific test args
        - --test-blobfuse-csi-driver
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-azure-blobfuse-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-blobfuse-csi-driver-e2e-vmss
      description: "Run E2E tests on a VMSS-based cluster for Blobfuse CSI driver."
      testgrid-num-columns-recent: '30'
