# sigs.k8s.io/kind presubmits
presubmits:
  kubernetes-sigs/kind:
  - name: pull-kind-build
    decorate: true
    path_alias: sigs.k8s.io/kind
    always_run: true
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-master
        command:
        - wrapper.sh
        - ./hack/ci/build-all.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
  - name: pull-kind-unit
    decorate: true
    path_alias: sigs.k8s.io/kind
    always_run: true
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-master
        command:
        - wrapper.sh
        - make
        - unit
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
  - name: pull-kind-verify
    decorate: true
    path_alias: sigs.k8s.io/kind
    always_run: true
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-experimental
        command:
        - wrapper.sh
        - ./hack/verify/all.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
  # mimic pull-kubernetes-e2e-kind, but using kind built in this PR
  - name: pull-kind-e2e-kubernetes
    always_run: true
    labels:
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kind
    decoration_config:
      timeout: 40m
      grace_period: 15m
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-master
        command:
        - wrapper.sh
        - bash
        - -c
        - cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
        env:
        - name: FOCUS
          value: "."
        # TODO(bentheelder): reduce the skip list further
        # NOTE: changes should filter down to pull-kubernetes-e2e-kind-canary
        # and then pull-kubernetes-e2e-kind
        - name: SKIP
          value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing
        - name: PARALLEL
          value: "true"
        - name: BUILD_TYPE
          value: bazel
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "9000Mi"
            cpu: 7500m
  # conformance test against kubernetes master branch with `kind`, skipping
  # serial tests so it runs in ~20m
  # GA-only variant
  - name: pull-kind-conformance-parallel-ga-only
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    always_run: false
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kind
    decoration_config:
      timeout: 40m
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-master
        env:
        # skip serial tests and run with --ginkgo-parallel
        - name: "PARALLEL"
          value: "true"
        - name: GA_ONLY
          value: "true"
        - name: BUILD_TYPE
          value: bazel
        command:
        - wrapper.sh
        - bash
        - -c
        - cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  # conformance test against kubernetes master branch with `kind`, skipping
  # serial tests so it runs in ~20m
  # IPv6 enabled variant
  - name: pull-kind-conformance-parallel-ipv6
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    always_run: true
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kind
    decoration_config:
      timeout: 40m
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-master
        env:
        # skip serial tests and run with --ginkgo-parallel
        - name: "PARALLEL"
          value: "true"
        # enable IPV6 in bootstrap image
        - name: "DOCKER_IN_DOCKER_IPV6_ENABLED"
          value: "true"
        # tell kind CI script to use ipv6
        - name: "IP_FAMILY"
          value: "ipv6"
        - name: BUILD_TYPE
          value: bazel
        command:
        - wrapper.sh
        - bash
        - -c
        - cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  # conformance test against kubernetes master branch with `kind`, skipping
  # serial tests so it runs in ~20m
  # Dual Stack enabled variant
  - name: pull-kind-conformance-parallel-dual-stack-ipv4-ipv6
    always_run: false
    optional: true
    labels:
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kind
    decoration_config:
      timeout: 40m
      grace_period: 15m
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-master
        command:
        - wrapper.sh
        - bash
        - -c
        - cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
        env:
        - name: FOCUS
          value: \[Conformance\]|IPv6DualStack
        - name: PARALLEL
          value: "true"
        - name: IP_FAMILY
          value: DualStack
        # enable IPV6 in bootstrap image
        - name: "DOCKER_IN_DOCKER_IPV6_ENABLED"
          value: "true"
        - name: BUILD_TYPE
          value: bazel
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # TODO(BenTheElder): adjust these everywhere
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  # mimic pull-kubernetes-e2e-kind, but using kind built in this PR
  - name: pull-kind-e2e-kubernetes-1-18
    always_run: true
    labels:
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: release-1.18
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kind
    decoration_config:
      timeout: 40m
      grace_period: 15m
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-1.18
        command:
        - wrapper.sh
        - bash
        - -c
        - cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
        env:
        - name: FOCUS
          value: "."
        # TODO(bentheelder): reduce the skip list further
        # NOTE: changes should filter down to pull-kubernetes-e2e-kind-canary
        # and then pull-kubernetes-e2e-kind
        - name: SKIP
          value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Network.should.set.TCP.CLOSE_WAIT.timeout|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|should.provide.basic.identity|\[NodeFeature:PodReadinessGate\]
        - name: PARALLEL
          value: "true"
        - name: BUILD_TYPE
          value: bazel
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # TODO(BenTheElder): adjust these everywhere
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  # conformance test against kubernetes release-1.17 branch with `kind`, skipping
  # serial tests so it runs in ~20m
  - name: pull-kind-conformance-parallel-1-17
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    always_run: true
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: release-1.17
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kind
    decoration_config:
      timeout: 40m
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-1.17
        env:
        # skip serial tests and run with --ginkgo-parallel
        - name: "PARALLEL"
          value: "true"
        - name: BUILD_TYPE
          value: bazel
        command:
        - wrapper.sh
        - bash
        - -c
        - cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  # conformance test against kubernetes release-1.16 branch with `kind`, skipping
  # serial tests so it runs in ~20m
  - name: pull-kind-conformance-parallel-1-16
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    always_run: true
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: release-1.16
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kind
    decoration_config:
      timeout: 40m
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200712-5349a04-1.16
        env:
        # skip serial tests and run with --ginkgo-parallel
        - name: "PARALLEL"
          value: "true"
        - name: BUILD_TYPE
          value: bazel
        command:
        - wrapper.sh
        - bash
        - -c
        - cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  # conformance test against kubernetes release-1.15 branch with `kind`, skipping
  # serial tests so it runs in ~20m
  - name: pull-kind-conformance-parallel-1-15
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    always_run: true
    decorate: true
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: release-1.15
      path_alias: k8s.io/kubernetes
    path_alias: sigs.k8s.io/kind
    decoration_config:
      timeout: 40m
    spec:
      containers:
      - image: gcr.io/k8s-testimages/krte:v20200619-19b0ee3-1.15
        env:
        # skip serial tests and run with --ginkgo-parallel
        - name: "PARALLEL"
          value: "true"
        - name: BUILD_TYPE
          value: bazel
        command:
        - wrapper.sh
        - bash
        - -c
        - cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
