presubmits:
  kubernetes/kubernetes:
  # this replaces the bootstrap / scenario based job going forward
  - name: pull-kubernetes-integration
    always_run: true
    decorate: true
    skip_branches:
    - release-\d+.\d+ # per-release job
    annotations:
      fork-per-release: "true"
      testgrid-num-failures-to-alert: '10'
      testgrid-alert-stale-results-hours: '24'
      testgrid-create-test-group: 'true'
    path_alias: k8s.io/kubernetes
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - ./hack/jenkins/test-dockerized.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
periodics:
- interval: 1h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-integration-master
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-periodic-interval: 2h 2h 6h 24h
    fork-per-release-generic-suffix: "true"
    testgrid-dashboards: sig-release-master-blocking, google-unit
    testgrid-tab-name: integration-master
    testgrid-alert-email: kubernetes-release-team@googlegroups.com
    description: "Ends up running: make test-cmd test-integration"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      command:
      - runner.sh
      args:
      - ./hack/jenkins/test-dockerized.sh
      env:
      - name: SHORT
        value: --short=false
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 4
