presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-verify
    always_run: true
    decorate: true
    skip_branches:
    - release-\d+.\d+ # per-release job
    annotations:
      fork-per-release: "true"
      testgrid-num-failures-to-alert: '10'
      testgrid-alert-stale-results-hours: '24'
      testgrid-create-test-group: 'true'
    path_alias: k8s.io/kubernetes
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        imagePullPolicy: Always
        command:
        - runner.sh
        args:
        - ./hack/jenkins/verify-dockerized.sh
        env:
        - name: EXCLUDE_TYPECHECK
          value: "y"
        # this is now covered by pull-kubernetes-files-remake
        - name: EXCLUDE_FILES_REMAKE
          value: "y"
        - name: EXCLUDE_GODEP
          value: "y"
        - name: KUBE_VERIFY_GIT_BRANCH
          value: master
        - name: REPO_DIR
          value: /workspace/k8s.io/kubernetes
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
periodics:
- interval: 1h
  cluster: k8s-infra-prow-build
  name: ci-kubernetes-verify-master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-periodic-interval: 2h 2h 6h 24h
    fork-per-release-generic-suffix: "true"
    testgrid-dashboards: sig-release-master-blocking, google-unit
    testgrid-tab-name: verify-master
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-oncall@google.com, release-managers@kubernetes.io
    description: "Ends up running: make verify"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./hack/jenkins/verify-dockerized.sh
      env:
      - name: EXCLUDE_READONLY_PACKAGE
        value: "y"
      - name: KUBE_VERIFY_GIT_BRANCH
        value: master
      - name: REPO_DIR
        value: /workspace/k8s.io/kubernetes
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 6
