periodics:
- interval: 12h
  name: ci-kubernetes-e2e-storage-selinux
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-storage-selinux.test-cncf-aws.k8s.io
      - --deployment=kops
      - --env=KUBE_SSH_USER=centos
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release-dev/ci/k8s-master.txt
      - --extract=ci/k8s-master
      - --ginkgo-parallel
      - --kops-image=679593333241/CentOS Linux 7 x86_64 HVM EBS ENA 2002_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-0042af67f8e4dcc20.4
      - --kops-args=--master-image=099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200609
      - --kops-overrides=spec.docker.selinuxEnabled=true
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-ssh-user=centos
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[sig-storage\].*\[Slow\] --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=120m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
      imagePullPolicy: Always
  annotations:
    testgrid-num-columns-recent: '20'
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-email: kubernetes-sig-storage-test-failures@googlegroups.com
