presubmits:
  kubernetes/release:
  - name: pull-release-cluster-up
    always_run: true
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-pull-kubernetes-e2e: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes
        - --repo=k8s.io/release=$(PULL_REFS)
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=90
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --down=false
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-nodes=4
        - --gcp-zone=us-west1-b
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-release-cluster-up
        - --test_args=--ginkgo.focus=definitely-not-a-real-focus
        - --timeout=65m
        image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: release-cluster-up
      testgrid-alert-email: release-managers@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-release-test
    always_run: true
    decorate: true
    path_alias: k8s.io/release
    extra_refs:
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci-bazel:latest
        command:
        - ../test-infra/hack/bazel.sh
        args:
        - test
        - //...
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: release-test
      testgrid-alert-email: release-managers@kubernetes.io
      testgrid-num-columns-recent: '30'
periodics:
# package tests
- name: periodic-release-verify-packages-debs
  interval: 6h
  annotations:
    testgrid-alert-email: release-managers@kubernetes.io
    testgrid-dashboards: sig-release-releng-informing
    testgrid-tab-name: verify-packages-debs
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: release
    base_ref: master
    path_alias: k8s.io/release
  spec:
    containers:
    - image: quay.io/k8s/release-tools:latest
      imagePullPolicy: Always
      command:
      - make
      - verify-published-debs
  rerun_auth_config:
    github_team_ids:
      - 2241179 # release-managers
- name: periodic-release-verify-packages-rpms
  interval: 6h
  annotations:
    testgrid-alert-email: release-managers@kubernetes.io
    testgrid-dashboards: sig-release-releng-informing
    testgrid-tab-name: verify-packages-rpms
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: release
    base_ref: master
    path_alias: k8s.io/release
  spec:
    containers:
    - image: quay.io/k8s/release-tools-centos:latest
      imagePullPolicy: Always
      command:
      - make
      - verify-published-rpms
  rerun_auth_config:
    github_team_ids:
      - 2241179 # release-managers
