periodics:
- name: periodic-cluster-api-provider-azure-conformance-v1alpha3
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 12h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: master
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
    - org: kubernetes
      repo: kubernetes
      base_ref: v1.18.3
      path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
          - "runner.sh"
          - "./scripts/ci-entrypoint.sh"
        env:
          - name: FOCUS
            value: "\\[Conformance\\]|\\[NodeConformance\\]"
          - name: SKIP
            value: "\\[Slow\\]|\\[Serial\\]|\\[Flaky\\]"
          - name: PARALLEL
            value: "true"
          - name: KUBERNETES_VERSION
            value: "v1.18.3"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1
            memory: "4Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: periodic-conformance-v1alpha3
- name: periodic-cluster-api-provider-azure-capi-e2e
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 12h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: master
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-experimental
      command:
      - "runner.sh"
      - "./scripts/ci-e2e.sh"
      env:
        - name: GINKGO_FOCUS
          value: "Cluster API E2E tests"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: periodic-capi-e2e
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
