presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gci-gce-ipvs
    always_run: false
    run_if_changed: '^pkg/.*/ipvs/'
    optional: true
    skip_report: false
    annotations:
      testgrid-create-test-group: "true"
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-pull-kubernetes-e2e: "true"
      preset-pull-kubernetes-e2e-gce: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=105
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env=KUBE_PROXY_MODE=ipvs
        - --extract=local
        - --gcp-node-image=ubuntu
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gci-gce-ipvs
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
        - --timeout=80m # thinking about making this longer? don't! 80m is a hard cap, and should get down to no more than 60m.
        image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        resources:
          requests:
            memory: "6Gi"

  kubernetes/dns:
  - name: pull-kubernetes-dns-test
    branches:
    - master
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20200205-602500d
        args:
        - --repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)
        - --root=/go/src
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --scenario=execute
        - --
        - "true"

periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gce-alpha-api
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      # List GCE Alpha features we want to enable, separated by commas.
      - --env=GCE_ALPHA_FEATURES=NetworkTiers
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=4
      - --gcp-project=k8s-e2e-gce-alpha-api-access
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:GCEAlphaFeature\] --minStartupPods=8
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: google-gce, sig-network-gce
    testgrid-tab-name: gce-alpha-api
    testgrid-alert-email: kubernetes-sig-network-test-failures@googlegroups.com
- interval: 6h
  name: ci-kubernetes-e2e-gce-coredns-performance
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-coredns-perf
      - --env=CLUSTER_DNS_CORE_DNS=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=3
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:PerformanceDNS\]
      - --timeout=60m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-network-gce
    testgrid-tab-name: gce-coredns-performance
- interval: 6h
  name: ci-kubernetes-e2e-gce-kubedns-performance
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-kubedns-perf
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=3
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:PerformanceDNS\]
      - --timeout=60m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-network-gce
    testgrid-tab-name: gce-kubedns-performance
- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-coredns
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --env=CLUSTER_DNS_CORE_DNS=true
      - --extract=ci/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master

- interval: 6h
  name: ci-kubernetes-e2e-gce-coredns-performance-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-coredns-perf-cache
      - --env=CLUSTER_DNS_CORE_DNS=true
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=3
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:PerformanceDNS\]
      - --timeout=60m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-network-gce
    testgrid-tab-name: gce-coredns-performance-nodecache
- interval: 6h
  name: ci-kubernetes-e2e-gce-kubedns-performance-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-kubedns-perf-cache
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=3
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:PerformanceDNS\]
      - --timeout=60m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-network-gce
    testgrid-tab-name: gce-kubedns-performance-nodecache
- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-coredns-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --env=CLUSTER_DNS_CORE_DNS=true
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-ingress
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=340
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=GCE_ALPHA_FEATURES=NetworkEndpointGroup
      - --env=KUBE_GCE_ENABLE_IP_ALIASES=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-project-type=ingress-project
      - --gcp-zone=asia-southeast1-a
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:Ingress\]|\[Feature:NEG\]
      - --timeout=320m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-release-master-blocking, google-gce, sig-network-gce
    testgrid-tab-name: gci-gce-ingress
    testgrid-alert-email: kubernetes-sig-network-test-failures@googlegroups.com
    description: Uses kubetest to run e2e tests (+Feature:Ingress|NEG) against a cluster created with cluster/kube-up.sh
    testgrid-alert-stale-results-hours: '24'
- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-ingress-manual-network
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=200
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=CREATE_CUSTOM_NETWORK=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-project-type=ingress-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:Ingress\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: sig-network-gce
    testgrid-tab-name: gci-gce-ingress-manual-network
    testgrid-alert-email: kubernetes-sig-network-test-failures@googlegroups.com
    testgrid-alert-stale-results-hours: '24'
- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-ip-alias
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=70
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=KUBE_GCE_ENABLE_IP_ALIASES=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=4
      - --gcp-project=k8s-jenkins-gce-gci-ip-aliases
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=50m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-dashboards: google-gce, google-gci
    testgrid-tab-name: ip-alias
- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-ipvs
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=KUBE_PROXY_MODE=ipvs
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=ubuntu
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
  annotations:
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-stale-results-hours: '24'
- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-kube-dns
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --extract=ci/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master

- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-kube-dns-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-serial-kube-dns
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=520
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=NODE_LOCAL_SSDS_EXT=1,scsi,fs
      - --env=CLUSTER_DNS_CORE_DNS=false,
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=500m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-serial-kube-dns-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=520
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=NODE_LOCAL_SSDS_EXT=1,scsi,fs
      - --env=CLUSTER_DNS_CORE_DNS=false,
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=500m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master

- interval: 12h
  name: ci-kubernetes-e2e-gci-gce-basic-sctp
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=320
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=KUBE_FEATURE_GATES=SCTPSupport=true
      - --env=ALLOW_PRIVILEGED=true
      - --env=NET_PLUGIN=kubenet
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:SCTP\] --ginkgo.skip=\[Feature:NetworkPolicy\]
      - --timeout=300m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
