presubmits:
  kubernetes/cloud-provider-gcp:
  - name: cloud-provider-gcp-tests
    always_run: true
    decorate: true
    path_alias: k8s.io/cloud-provider-gcp
    annotations:
      testgrid-dashboards: provider-gcp-presubmits
      description: Build and unit test for kubernetes/cloud-provider-gcp.
      testgrid-num-columns-recent: '30'
    extra_refs:
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    spec:
      containers:
      - image: gcr.io/cloud-builders/bazel
        command:
        - ../test-infra/hack/bazel.sh
        args:
        - test
        - --test_output=errors
        - --
        - //...
        - -//vendor/...
  - name: cloud-provider-gcp-e2e-create
    always_run: true
    decorate: true
    path_alias: k8s.io/cloud-provider-gcp
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    annotations:
      testgrid-dashboards: provider-gcp-presubmits
      description: End to end cluster creation test using cluster/kube-up based on kubernetes/cloud-provider-gcp.
      testgrid-num-columns-recent: '30'
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200710-6b3b6fe-master
        command:
        - runner.sh
        args:
        - test/e2e.sh
